opensearch

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -29,11 +29,34 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
-    # Mongo DB
-    - name: Start MongoDB service
+    # OpenSearch
+    - name: Set up OpenSearch
+      uses: ankane/setup-opensearch@v1
+      with:
+        opensearch-version: 2.19.2  # Specify a version >= 2.4 for Windows compatibility
+
+    - name: Change OpenSearch HTTP port to 9250
+      shell: pwsh
       run: |
-        Set-Service -Name 'MongoDB' -StartupType Automatic
-        Start-Service -Name 'MongoDB'
+        $configPath = "$env:OPENSEARCH_HOME\config\opensearch.yml"
+        if (Test-Path $configPath) {
+          Add-Content -Path $configPath -Value "`nhttp.port: 9250"
+        } else {
+          Write-Error "OpenSearch configuration file not found at $configPath"
+          exit 1
+        } 
+        
+    - name: Start OpenSearch
+      shell: pwsh
+      run: |
+        Start-Process -FilePath "$env:OPENSEARCH_HOME\bin\opensearch.bat" -NoNewWindow
+        Start-Sleep -Seconds 10  # Wait for OpenSearch to initialize
+
+    # # Mongo DB
+    # - name: Start MongoDB service
+    #   run: |
+    #     Set-Service -Name 'MongoDB' -StartupType Automatic
+    #     Start-Service -Name 'MongoDB'
 
     # # RavenDB
     # - name: Install RavenDB 
@@ -117,9 +140,8 @@ jobs:
 
     - name: Run tests
       run: |
-        #dotnet test .\Audit.NET.sln --no-build -c release --filter "TestCategory!=Integration|TestCategory=AzureCosmos|TestCategory=AzureBlobs|TestCategory=AzureTables|TestCategory=RavenDB|TestCategory=Mongo" --logger "console;verbosity=normal" --logger "trx;LogFilePrefix=VSTest" "-m:1" --results-directory "./test/TestResult"
-        dotnet test .\test\Audit.MongoClient.UnitTest --no-build -c release --filter "TestCategory=Mongo" --logger "console;verbosity=normal" --logger "trx;LogFilePrefix=VSTest" "-m:1" --results-directory "./test/TestResult"
-        dotnet test .\test\Audit.MongoDB.UnitTest --no-build -c release --filter "TestCategory=Mongo" --logger "console;verbosity=normal" --logger "trx;LogFilePrefix=VSTest" "-m:1" --results-directory "./test/TestResult"
+        #dotnet test .\Audit.NET.sln --no-build -c release --filter "TestCategory!=Integration|TestCategory=AzureCosmos|TestCategory=AzureBlobs|TestCategory=AzureTables|TestCategory=RavenDB|TestCategory=Mongo|TestCategory=OpenSearch" --logger "console;verbosity=normal" --logger "trx;LogFilePrefix=VSTest" "-m:1" --results-directory "./test/TestResult"
+        dotnet test .\test\Audit.OpenSearch.UnitTest --no-build -c release --filter "TestCategory=OpenSearch" --logger "console;verbosity=normal" --logger "trx;LogFilePrefix=VSTest" "-m:1" --results-directory "./test/TestResult"
 
     - name: Generate Code Coverage Report
       run: |
